# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: python/gamemaster.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'python/gamemaster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17python/gamemaster.proto\"*\n\nGameMaster\x12\x1c\n\ttemplates\x18\x02 \x03(\x0b\x32\t.Template\"<\n\x08Template\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x1b\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\r.TemplateData\"\x95\x01\n\x0cTemplateData\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12*\n\x10pokemon_settings\x18\x02 \x01(\x0b\x32\x10.PokemonSettings\x12\"\n\x0cpokemon_type\x18\x08 \x01(\x0b\x32\x0c.PokemonType\x12 \n\x0b\x63ombat_move\x18% \x01(\x0b\x32\x0b.CombatMove\"\xaf\x01\n\x0fPokemonSettings\x12\x11\n\tpokemonId\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\r\n\x05type2\x18\x05 \x01(\x05\x12#\n\x0cpokemonStats\x18\x08 \x01(\x0b\x32\r.PokemonStats\x12\x12\n\nquickMoves\x18\t \x01(\x0c\x12\x16\n\x0e\x63inematicMoves\x18\n \x01(\x0c\x12\x1b\n\x13\x65liteCinematicMoves\x18\x32 \x01(\x0c\"L\n\x0cPokemonStats\x12\x13\n\x0b\x62\x61seStamina\x18\x01 \x01(\x05\x12\x12\n\nbaseAttack\x18\x02 \x01(\x05\x12\x13\n\x0b\x62\x61seDefense\x18\x03 \x01(\x05\"2\n\x0bPokemonType\x12\x15\n\reffectiveness\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\x05\"\x8a\x01\n\nCombatMove\x12\x0e\n\x06moveId\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05power\x18\x03 \x01(\x02\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\rdurationTurns\x18\x05 \x01(\x05\x12\x13\n\x0b\x65nergyDelta\x18\x06 \x01(\x04\x12\x15\n\x05\x62uffs\x18\x07 \x01(\x0b\x32\x06.Buffs\"\xbf\x01\n\x05\x42uffs\x12%\n\x1d\x61ttackerAttackStatStageChange\x18\x01 \x01(\x05\x12&\n\x1e\x61ttackerDefenseStatStageChange\x18\x02 \x01(\x05\x12#\n\x1btargetAttackStatStageChange\x18\x03 \x01(\x05\x12$\n\x1ctargetDefenseStatStageChange\x18\x04 \x01(\x05\x12\x1c\n\x14\x62uffActivationChance\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python.gamemaster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEMASTER']._serialized_start=27
  _globals['_GAMEMASTER']._serialized_end=69
  _globals['_TEMPLATE']._serialized_start=71
  _globals['_TEMPLATE']._serialized_end=131
  _globals['_TEMPLATEDATA']._serialized_start=134
  _globals['_TEMPLATEDATA']._serialized_end=283
  _globals['_POKEMONSETTINGS']._serialized_start=286
  _globals['_POKEMONSETTINGS']._serialized_end=461
  _globals['_POKEMONSTATS']._serialized_start=463
  _globals['_POKEMONSTATS']._serialized_end=539
  _globals['_POKEMONTYPE']._serialized_start=541
  _globals['_POKEMONTYPE']._serialized_end=591
  _globals['_COMBATMOVE']._serialized_start=594
  _globals['_COMBATMOVE']._serialized_end=732
  _globals['_BUFFS']._serialized_start=735
  _globals['_BUFFS']._serialized_end=926
# @@protoc_insertion_point(module_scope)
